# Generated by Django 2.2 on 2019-11-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20191114_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-name',), 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Список характеристик'},
        ),
    ]
